### ISSUE TITLE
It fails on first http request on Solaris

### ISSUE THREAD

**Issue by OleksandrBezhan** [ajaxorg/cloud9#3254]
When I run the instance of cloud9 on Solaris OS I'm getting exception:

```
Exception found:
Process terminated with code 1, find: illegal option -- O
find: [-H | -L] path-list predicate-list

at Object.handle (/home/itraccn1/cloud9/cloud9/plugins-server/cloud9.core/middleware.js:18:19)
    at next (/home/itraccn1/cloud9/cloud9/node_modules/connect/lib/http.js:199:17)
    at /home/itraccn1/cloud9/cloud9/node_modules/connect/lib/middleware/router.js:177:23
    at /home/itraccn1/cloud9/cloud9/plugins-server/cloud9.ide.filelist/filelist-plugin.js:86:36
    at ChildProcess.<anonymous> (/home/itraccn1/cloud9/cloud9/plugins-server/cloud9.ide.filelist/filelist.js:65:17)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

I add `console.log` into `filelist.js:45`:
```console.log(args);```

And here is the output:
```
-n,10,find,-O3,-P,.,-type,f,-mount,-a,(,!,-regex,.*/\..*,-or,-name,.htaccess,),(,!,-regex,.*\/\.gz$,),(,!,-regex,.*\/\.bzr$,),(,!,-regex,.*\/\.cdv$,),(,!,-regex,.*\/\.dep$,),(,!,-regex,.*\/\.dot$,),(,!,-regex,.*\/\.nib$,),(,!,-regex,.*\/\.plst$,),(,!,-regex,.*\/_darcs$,),(,!,-regex,.*\/_sgbak$,),(,!,-regex,.*\/autom4te\.cache$,),(,!,-regex,.*\/cover_db$,),(,!,-regex,.*\/_build$,),(,!,-regex,.*\/\.tmp$,),(,!,-regex,.*\/\.pyc$,),(,!,-regex,.*\/\.class$,),(,!,-regex,.*\/\.c9revisions\/.*,),(,!,-regex,.*\/\.architect\/.*,),(,!,-regex,.*\/\.sourcemint\/.*,),(,!,-regex,.*\/\.git\/.*,),(,!,-regex,.*\/\.hg\/.*,),(,!,-regex,.*\/\.pc\/.*,),(,!,-regex,.*\/\.svn\/.*,),(,!,-regex,.*\/blib\/.*,),(,!,-regex,.*\/CVS\/.*,),(,!,-regex,.*\/RCS\/.*,),(,!,-regex,.*\/SCCS\/.*,),(,!,-regex,.*\/\.DS_Store\/.*,),(,!,-path,/proc,),(,!,-path,/sys,),(,!,-path,/mnt,),-regextype,posix-extended,-print
```

It seems like Solaris doesn't support -O option and probably some other options/commands, that the server generates. Is there any Cloud9 package/plugin/guide for Solaris ?

Thanks.

**Comment by mikl0s** [comment]
Same issue with FreeBSD 9.2
