### ISSUE TITLE
Unhandled 'error' event in events.js:72

### ISSUE THREAD

**Issue by mikl0s** [ajaxorg/cloud9#3259]
Fresh jail on a FreeBSD 9.2.

pkg install npm node libxml2 git
git clone https://github.com/ajaxorg/cloud9.git
cd cloud9
npm install

```
[mikkel@cloud9 /usr/home/mikkel/cloud9]$ bin/cloud9.sh -l 0.0.0.0
FreeBSD 64 bit
connect plugin start
Connect server listening at http://0.0.0.0:3131
IDE SERVER PLUGIN:  auth
IDE SERVER PLUGIN:  git
IDE SERVER PLUGIN:  gittools
IDE SERVER PLUGIN:  hg
IDE SERVER PLUGIN:  npm
IDE SERVER PLUGIN:  filelist
IDE SERVER PLUGIN:  search
IDE SERVER PLUGIN:  revisions
IDE SERVER PLUGIN:  settings
IDE SERVER PLUGIN:  shell
IDE SERVER PLUGIN:  state
IDE SERVER PLUGIN:  watcher
IDE SERVER PLUGIN:  node-runtime
IDE SERVER PLUGIN:  npm-runtime
IDE SERVER PLUGIN:  python-runtime
IDE SERVER PLUGIN:  apache-runtime
IDE SERVER PLUGIN:  ruby-runtime
IDE SERVER PLUGIN:  php-runtime
Started '/usr/home/mikkel/cloud9/configs/default'!
IDE server initialized. Listening on 0.0.0.0:3131
Exception found:
Process terminated with code 1,
Process terminated with code 1,
    at Object.handle (/usr/home/mikkel/cloud9/plugins-server/cloud9.core/middleware.js:18:19)
    at next (/usr/home/mikkel/cloud9/node_modules/connect/lib/http.js:199:17)
    at /usr/home/mikkel/cloud9/node_modules/connect/lib/middleware/router.js:177:23
    at /usr/home/mikkel/cloud9/plugins-server/cloud9.ide.filelist/filelist-plugin.js:86:36
    at ChildProcess.<anonymous> (/usr/home/mikkel/cloud9/plugins-server/cloud9.ide.filelist/filelist.js:65:17)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by mingfang** [comment]
+1

**Comment by Rodrive** [comment]
Same problem here
