### ISSUE TITLE
error when launching cloud9 server after installation on ubuntu running on a remote server

### ISSUE THREAD

**Issue by sviosdi** [ajaxorg/cloud9#3260]
I have installed cloud9 as explained in the README.md
I launch it with : bin/cloud9.sh -l 0.0.0.0
it runs : IDE server initialized. Listening on 0.0.0.0:3131
but when opening it in the browser : "http:mydomain.com:3131"
it's loading, opening, and then crashing with that message :
`events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)`

**Comment by sviosdi** [comment]
it's now working after installing mercurial
